import {
  Boxes,
  ChartNoAxesCombined,
  CheckSquare,
  Clipboard,
  Code2,
  CornerUpRight,
  FileText,
  Globe,
  GraduationCap,
  Languages,
  Lightbulb,
  Link,
  ListChecks,
  Maximize,
  MessageCircle,
  Orbit,
  PenLine,
  Scan,
  ScanLine,
  Search,
  ShoppingBag,
  Sparkles,
  Table,
  Workflow,
} from "lucide-react";
import type { ComponentType } from "react";

export const HELIX_ACTION_ICONS: Record<string, ComponentType<{ className?: string }>> = {
  "message-circle": MessageCircle,
  clipboard: Clipboard,
  scan: Scan,
  globe: Globe,
  workflow: Workflow,
  orbit: Orbit,
  "list-checks": ListChecks,
  lightbulb: Lightbulb,
  languages: Languages,
  sparkles: Sparkles,
  maximize: Maximize,
  "scan-line": ScanLine,
  search: Search,
  link: Link,
  "check-square": CheckSquare,
  "shopping-bag": ShoppingBag,
  table: Table,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "code-2": Code2,
  "graduation-cap": GraduationCap,
  "pen-line": PenLine,
  boxes: Boxes,
  corner: CornerUpRight,
  file: FileText,
};
